apiVersion: v1
kind: Service
metadata:
  name: soundsystem
  namespace: soundsystem
  labels:
    app: soundsystem
spec:
  type: ClusterIP
  selector:
    app: soundsystem
  ports:
    - name: http
      port: 80
      targetPort: 8080
