replicaCount: 1
image:
  repository: ghcr.io/bala-kubelancer/soundsystem
  tag: "10f62eccf8bd54155498b3d5864fd468cc63ba55"
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
